import type { GeneratedFile } from "@/lib/types"

type BuildProjectFilesInput = {
  prompt: string
  originalPrompt?: string | null
  projectName?: string | null
  providerMessage?: string | null
  promptSummary?: string | null
}

type BuildProjectFilesOutput = {
  message: string
  files: GeneratedFile[]
}

export function buildProjectFiles({
  prompt,
  originalPrompt,
  projectName,
  providerMessage,
  promptSummary,
}: BuildProjectFilesInput): BuildProjectFilesOutput {
  const name = sanitizeName(projectName || inferName(prompt) || "Swift Starter")
  const isDashboard = /(dashboard|admin|analytics|report|metric|kpi|sidebar)/i.test(prompt)
  const isCommerce = /(marketplace|e-?commerce|shop|store|product|cart|checkout|shopee)/i.test(prompt)
  const brief = promptSummary || prompt

  const baseFiles = buildStandardStructureFiles(name)
  const domainOverrides = isDashboard
    ? buildDashboardOverrideFiles(name, brief)
    : isCommerce
      ? buildCommerceOverrideFiles(name, brief)
      : buildGenericOverrideFiles(name, brief)

  const readme = buildReadmeFile({
    name,
    originalPrompt: originalPrompt || prompt,
    effectivePrompt: prompt,
    providerMessage,
  })

  const files = mergeFilesByPath([...baseFiles, readme], domainOverrides)

  return {
    message: `Generated a full-stack starter for ${name} using the standard Swift project tree.`,
    files,
  }
}

function buildStandardStructureFiles(name: string): GeneratedFile[] {
  const safeName = serializeForCode(name)

  return [
    {
      path: "app/layout.tsx",
      language: "tsx",
      content: `import "./globals.css"

export const metadata = {
  title: ${safeName},
  description: "Generated by Swift Builder",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
    },
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `export default function HomePage() {
  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-20 text-white">
      <section className="mx-auto max-w-4xl rounded-3xl border border-white/10 bg-white/5 p-10">
        <h1 className="text-4xl font-semibold">Starter Project</h1>
        <p className="mt-4 text-neutral-300">Update this page from Code tab.</p>
      </section>
    </main>
  )
}
`,
    },
    {
      path: "app/globals.css",
      language: "css",
      content: `:root {
  --background: #0a0a0a;
  --foreground: #fafafa;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: var(--background);
  color: var(--foreground);
  font-family: Inter, system-ui, sans-serif;
}
`,
    },
    {
      path: "app/api/health/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({ ok: true, service: "swift-generated-app" })
}
`,
    },
    {
      path: "app/api/generate/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null)
  return NextResponse.json({ ok: true, received: body })
}
`,
    },
    {
      path: "app/api/projects/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({ projects: [] })
}
`,
    },
    {
      path: "app/api/models/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export async function GET() {
  return NextResponse.json({
    models: [
      { key: "default", label: "Default", provider: "openai", price: 2000 },
    ],
  })
}
`,
    },
    {
      path: "components/ui/button.tsx",
      language: "tsx",
      content: `type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>

export function Button({ className = "", ...props }: ButtonProps) {
  return (
    <button
      className={"inline-flex items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium text-black " + className}
      {...props}
    />
  )
}
`,
    },
    {
      path: "components/ui/card.tsx",
      language: "tsx",
      content: `export function Card({ children }: { children: React.ReactNode }) {
  return <div className="rounded-lg border border-white/10 bg-white/5 p-6">{children}</div>
}
`,
    },
    {
      path: "components/dashboard/sidebar.tsx",
      language: "tsx",
      content: `export function DashboardSidebar() {
  return (
    <aside className="w-64 border-r border-white/10 p-4 text-sm text-neutral-300">
      <p className="font-semibold text-white">Sidebar</p>
      <ul className="mt-4 space-y-2">
        <li>Dashboard</li>
        <li>Projects</li>
        <li>Settings</li>
      </ul>
    </aside>
  )
}
`,
    },
    {
      path: "components/editor/chat-panel.tsx",
      language: "tsx",
      content: `export function ChatPanel() {
  return <div className="rounded-lg border border-white/10 p-4">Chat Panel</div>
}
`,
    },
    {
      path: "components/editor/preview-panel.tsx",
      language: "tsx",
      content: `export function PreviewPanel() {
  return <div className="rounded-lg border border-white/10 p-4">Preview Panel</div>
}
`,
    },
    {
      path: "hooks/use-mobile.ts",
      language: "ts",
      content: `import { useEffect, useState } from "react"

export function useMobile(breakpoint = 768) {
  const [isMobile, setIsMobile] = useState(false)

  useEffect(() => {
    const update = () => setIsMobile(window.innerWidth < breakpoint)
    update()
    window.addEventListener("resize", update)
    return () => window.removeEventListener("resize", update)
  }, [breakpoint])

  return isMobile
}
`,
    },
    {
      path: "hooks/use-toast.ts",
      language: "ts",
      content: `type Toast = { title: string; description?: string }

export function useToast() {
  return {
    toast(toast: Toast) {
      console.log("toast", toast)
    },
  }
}
`,
    },
    {
      path: "lib/env.ts",
      language: "ts",
      content: `export const env = {
  nodeEnv: process.env.NODE_ENV || "development",
  databaseUrl: process.env.DATABASE_URL || "",
  openAiApiKey: process.env.OPENAI_API_KEY || "",
}
`,
    },
    {
      path: "lib/utils.ts",
      language: "ts",
      content: `export function cn(...parts: Array<string | false | null | undefined>) {
  return parts.filter(Boolean).join(" ")
}
`,
    },
    {
      path: "lib/store.ts",
      language: "ts",
      content: `type AppState = {
  activeProjectId: string | null
}

export const appStore: AppState = {
  activeProjectId: null,
}
`,
    },
    {
      path: "lib/ai/config.ts",
      language: "ts",
      content: `export const AI_CONFIG = {
  provider: "openai",
  model: process.env.OPENAI_DEFAULT_MODEL || "gpt-4o-mini",
  timeoutMs: Number(process.env.AI_TIMEOUT_MS || 60000),
}
`,
    },
    {
      path: "lib/ai/client.ts",
      language: "ts",
      content: `import { AI_CONFIG } from "./config"

export async function generateText(prompt: string) {
  return {
    provider: AI_CONFIG.provider,
    model: AI_CONFIG.model,
    message: "Generated response for: " + prompt,
  }
}
`,
    },
    {
      path: "lib/services/project.service.ts",
      language: "ts",
      content: `type Project = { id: string; name: string; updatedAt: string }

export function listProjects(): Project[] {
  return []
}
`,
    },
    {
      path: "prisma/schema.prisma",
      language: "prisma",
      content: `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Project {
  id        String   @id @default(cuid())
  name      String
  prompt    String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`,
    },
    {
      path: "public/site.webmanifest",
      language: "json",
      content: `{
  "name": "Swift Generated App",
  "short_name": "SwiftApp",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#0a0a0a",
  "theme_color": "#0a0a0a"
}
`,
    },
    
    {
      path: ".env.example",
      language: "env",
      content: `DATABASE_URL="file:./dev.db"
NEXTAUTH_SECRET="replace-me"
OPENAI_API_KEY="replace-me"
OPENAI_DEFAULT_MODEL="gpt-4o-mini"
AI_PRIMARY_PROVIDER="openai"
`,
    },
    {
      path: "auth.ts",
      language: "ts",
      content: `export const authConfig = {
  providers: ["credentials", "google"],
}
`,
    },
    {
      path: "components.json",
      language: "json",
      content: `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
`,
    },
    {
      path: "middleware.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"

export function middleware() {
  return NextResponse.next()
}
`,
    },
    {
      path: "next.config.mjs",
      language: "ts",
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    unoptimized: true,
  },
}

export default nextConfig
`,
    },
    {
      path: "package.json",
      language: "json",
      content: `{
  "name": "swift-generated-app",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "16.2.0",
    "react": "19.2.4",
    "react-dom": "19.2.4"
  },
  "devDependencies": {
    "typescript": "5.7.3"
  }
}
`,
    },
    {
      path: "postcss.config.mjs",
      language: "ts",
      content: `export default {
  plugins: {},
}
`,
    },
    {
      path: "tsconfig.json",
      language: "json",
      content: `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
`,
    },
    {
      path: "styles/globals.css",
      language: "css",
      content: `/* global styles (no Tailwind) */
html, body { height: 100%; }
body { margin: 0; font-family: Inter, system-ui, sans-serif; }
`,
    }
  ]
}

function buildGenericOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-20 text-white">
      <section className="mx-auto max-w-4xl rounded-3xl border border-white/10 bg-white/5 p-10">
        <h1 className="text-4xl font-semibold">{projectName}</h1>
        <p className="mt-4 text-neutral-300">Build brief: {buildBrief}</p>
        <p className="mt-3 text-sm text-neutral-400">
          This output follows Swift standard structure: app, components, hooks, lib, prisma, public, styles.
        </p>
      </section>
    </main>
  )
}
`,
    },
  ]
}

function buildDashboardOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `const stats = [
  { label: "Revenue", value: "Rp 128.450.000", trend: "+12.4%" },
  { label: "Orders", value: "2,481", trend: "+8.1%" },
  { label: "Active Users", value: "9,204", trend: "+5.9%" },
  { label: "Conversion", value: "3.42%", trend: "+0.3%" },
]

const activities = [
  { title: "Invoice #INV-0324 paid", time: "2 minutes ago" },
  { title: "New user signed up", time: "9 minutes ago" },
  { title: "Project deployment completed", time: "23 minutes ago" },
  { title: "Payment method updated", time: "1 hour ago" },
]

export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 text-white">
      <div className="mx-auto grid max-w-7xl gap-6 px-4 py-6 md:grid-cols-[260px_1fr]">
        <aside className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
          <p className="text-xs uppercase tracking-[0.2em] text-emerald-300">Workspace</p>
          <h1 className="mt-3 text-2xl font-semibold">{projectName}</h1>
          <p className="mt-2 text-sm text-neutral-400">Dashboard fallback mode</p>
          <nav className="mt-6 space-y-2 text-sm text-neutral-300">
            <a className="block rounded-lg bg-white/10 px-3 py-2">Overview</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Analytics</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Projects</a>
            <a className="block rounded-lg px-3 py-2 hover:bg-white/5">Settings</a>
          </nav>
        </aside>

        <section className="space-y-6">
          <header className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <h2 className="text-2xl font-semibold">Dashboard Overview</h2>
            <p className="mt-2 text-sm text-neutral-300">Build brief: {buildBrief}</p>
          </header>

          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            {stats.map((item) => (
              <article key={item.label} className="rounded-xl border border-white/10 bg-white/[0.03] p-4">
                <p className="text-xs uppercase tracking-wide text-neutral-400">{item.label}</p>
                <p className="mt-2 text-2xl font-semibold">{item.value}</p>
                <p className="mt-1 text-xs text-emerald-300">{item.trend}</p>
              </article>
            ))}
          </div>

          <article className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
            <h3 className="text-lg font-semibold">Recent Activity</h3>
            <ul className="mt-4 space-y-3 text-sm text-neutral-300">
              {activities.map((activity) => (
                <li key={activity.title} className="flex items-center justify-between rounded-lg bg-white/[0.02] px-3 py-2">
                  <span>{activity.title}</span>
                  <span className="text-xs text-neutral-500">{activity.time}</span>
                </li>
              ))}
            </ul>
          </article>
        </section>
      </div>
    </main>
  )
}
`,
    },
    {
      path: "app/api/dashboard/summary/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"
import { getDashboardSummary } from "@/lib/services/dashboard.service"

export async function GET() {
  const summary = await getDashboardSummary()
  return NextResponse.json(summary)
}
`,
    },
    {
      path: "lib/services/dashboard.service.ts",
      language: "ts",
      content: `export async function getDashboardSummary() {
  return {
    revenue: 128450000,
    orders: 2481,
    activeUsers: 9204,
    conversionRate: 3.42,
  }
}
`,
    },
  ]
}

function buildCommerceOverrideFiles(name: string, prompt: string): GeneratedFile[] {
  const safeName = serializeForCode(name)
  const safePrompt = serializeForCode(escapeInlineText(prompt))

  return [
    {
      path: "app/page.tsx",
      language: "tsx",
      content: `export default function HomePage() {
  const projectName = ${safeName}
  const buildBrief = ${safePrompt}

  return (
    <main className="min-h-screen bg-neutral-950 px-6 py-16 text-white">
      <section className="mx-auto max-w-5xl rounded-3xl border border-white/10 bg-gradient-to-br from-orange-500/25 via-orange-600/10 to-neutral-900 p-10">
        <span className="rounded-full border border-orange-300/30 px-3 py-1 text-xs tracking-[0.2em] text-orange-200">
          {projectName}
        </span>
        <h1 className="mt-5 text-4xl font-semibold leading-tight">Build a modern commerce storefront</h1>
        <p className="mt-3 max-w-2xl text-neutral-300">Build brief: {buildBrief}</p>
      </section>
    </main>
  )
}
`,
    },
    {
      path: "app/api/products/route.ts",
      language: "ts",
      content: `import { NextResponse } from "next/server"
import { listProducts } from "@/lib/services/catalog.service"

export async function GET() {
  const products = await listProducts()
  return NextResponse.json({ products, total: products.length })
}
`,
    },
    {
      path: "app/api/orders/route.ts",
      language: "ts",
      content: `import { NextRequest, NextResponse } from "next/server"

export async function POST(request: NextRequest) {
  const payload = await request.json()
  const customerName = payload?.customerName
  const items = payload?.items

  if (!customerName || !Array.isArray(items) || items.length === 0) {
    return NextResponse.json({ error: "customerName and items are required" }, { status: 400 })
  }

  return NextResponse.json({
    success: true,
    order: {
      id: "ord-" + Date.now(),
      customerName,
      itemCount: items.length,
      status: "pending-payment",
    },
  })
}
`,
    },
    {
      path: "lib/services/catalog.service.ts",
      language: "ts",
      content: `type Product = {
  id: string
  name: string
  price: number
  stock: number
}

const mockProducts: Product[] = [
  { id: "prod-1", name: "Starter Item", price: 149000, stock: 20 },
  { id: "prod-2", name: "Popular Item", price: 299000, stock: 50 },
  { id: "prod-3", name: "Premium Item", price: 499000, stock: 15 },
]

export async function listProducts(): Promise<Product[]> {
  return mockProducts
}
`,
    },
    {
      path: "prisma/schema.prisma",
      language: "prisma",
      content: `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Product {
  id          String   @id @default(cuid())
  name        String
  slug        String   @unique
  description String
  price       Int
  stock       Int
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}

model Order {
  id           String   @id @default(cuid())
  customerName String
  status       String   @default("pending-payment")
  totalAmount  Int
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
}
`,
    },
  ]
}

function buildReadmeFile({
  name,
  originalPrompt,
  effectivePrompt,
  providerMessage,
}: {
  name: string
  originalPrompt: string
  effectivePrompt: string
  providerMessage?: string | null
}): GeneratedFile {
  return {
    path: "README.md",
    language: "md",
    content: `# ${escapeMultilineText(name)}

Generated with fixed Swift project structure.

## Included Root Tree

- app/
- components/
- hooks/
- lib/
- prisma/
- public/
- styles/
- .env.example
- auth.ts
- components.json
- middleware.ts
- next.config.mjs
- package.json
- postcss.config.mjs
- tsconfig.json

## Original Prompt

> ${escapeMultilineText(originalPrompt)}

## Effective Build Brief

${escapeMultilineText(effectivePrompt)}

## Provider Summary

${escapeMultilineText(providerMessage || "Local scaffold fallback was used.")}
`,
  }
}

function mergeFilesByPath(base: GeneratedFile[], overrides: GeneratedFile[]) {
  const map = new Map<string, GeneratedFile>()

  for (const file of [...base, ...overrides]) {
    const normalizedPath = normalizePath(file.path)
    map.set(normalizedPath, {
      ...file,
      path: normalizedPath,
    })
  }

  return Array.from(map.values()).sort((a, b) => a.path.localeCompare(b.path))
}

function normalizePath(path: string) {
  return path.replace(/\\/g, "/").replace(/^\.\//, "")
}

function inferName(prompt: string) {
  const quoted = prompt.match(/["“](.+?)["”]/)
  if (quoted?.[1]) return quoted[1]

  const named = prompt.match(/(?:named|bernama|name)\s+([a-z0-9][a-z0-9\\s-]{2,30})/i)
  if (named?.[1]) return named[1].trim()

  return null
}

function sanitizeName(input: string) {
  const normalized = input.replace(/\s+/g, " ").trim()
  return normalized.slice(0, 40)
}

function escapeInlineText(value: string) {
  return value
    .replace(/\s+/g, " ")
    .trim()
    .replace(/`/g, "'")
    .replace(/\$/g, "\\$")
}

function escapeMultilineText(value: string) {
  return value.replace(/`/g, "'").replace(/\$/g, "\\$")
}

function serializeForCode(value: string) {
  return JSON.stringify(value).replace(/\$/g, "\\$")
}
